# Generated by Django 3.2.5 on 2022-02-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
