# Generated by Django 3.2.5 on 2022-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0005_delete_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('disease_id', models.IntegerField(blank=True, null=True)),
                ('prog_LM', models.IntegerField(blank=True, null=True)),
                ('prog_LM_th', models.IntegerField(blank=True, null=True)),
                ('prog_LM_pc', models.IntegerField(blank=True, null=True)),
                ('prog_TM', models.IntegerField(blank=True, null=True)),
                ('prog_TM_mcq', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
