# Generated by Django 3.2.5 on 2022-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='prog_LM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prog_LM_pc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prog_LM_th',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prog_TM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='prog_TM_mcq',
            field=models.IntegerField(default=0),
        ),
    ]
