# Generated by Django 3.2.5 on 2022-02-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220220_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='prog_TM_mcq',
        ),
    ]
