# Generated by Django 3.2.5 on 2022-02-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_progress_prog_tm_mcq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='disease_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='prog_LM',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='prog_LM_pc',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='prog_LM_th',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='prog_TM',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user_id',
        ),
    ]
