# Generated by Django 3.2.5 on 2022-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220220_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
