# Generated by Django 3.2.5 on 2022-03-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_delete_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('disease_id', models.IntegerField(blank=True, null=True)),
                ('prog_LM', models.IntegerField(default=0)),
                ('prog_LM_th', models.IntegerField(default=0)),
                ('prog_LM_pc', models.IntegerField(default=0)),
                ('prog_TM', models.IntegerField(default=0)),
                ('prog_TM_mcq', models.IntegerField(default=0)),
                ('theory_prog', models.IntegerField(blank=True, null=True)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
