# Generated by Django 3.2.5 on 2022-03-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='user_name',
        ),
    ]
