# Generated by Django 3.2.5 on 2022-03-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_progress_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
