# Generated by Django 3.2.5 on 2022-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20220305_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='kidney_LM_pc_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='kidney_LM_pc_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='kidney_LM_pc_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='kidney_LM_th',
            field=models.BooleanField(default=False),
        ),
    ]
