# Generated by Django 3.2.5 on 2022-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20220305_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='headneck_LM_pc_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='headneck_LM_pc_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='headneck_LM_pc_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='headneck_LM_th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='lung_LM_pc_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='lung_LM_pc_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='lung_LM_pc_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='lung_LM_th',
            field=models.BooleanField(default=False),
        ),
    ]
