# Generated by Django 3.2.5 on 2022-03-03 13:10

import casestudys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('myfiles', models.FileField(upload_to=casestudys.models.myuploadfile.upload_file)),
            ],
        ),
    ]
