# Generated by Django 3.2.5 on 2022-03-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('ques_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ques_txt', models.TextField(blank=True)),
                ('opt_A', models.TextField(blank=True)),
                ('opt_B', models.TextField(blank=True)),
                ('opt_C', models.TextField(blank=True)),
                ('opt_D', models.TextField(blank=True)),
                ('corr_opt', models.CharField(max_length=50)),
            ],
        ),
    ]
