# Generated by Django 3.2.5 on 2022-03-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='test_set',
            field=models.TextField(blank=True),
        ),
    ]
