# Generated by Django 3.2.5 on 2022-03-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_mcq_test_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='ques_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
