# Generated by Django 3.2.5 on 2022-03-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_mcq_ques_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('test_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testcases.mcq')),
            ],
        ),
    ]
