# Generated by Django 3.2.5 on 2022-03-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_mcq_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq_score',
            old_name='test_set',
            new_name='test_set_new',
        ),
    ]
