# Generated by Django 3.2.5 on 2022-03-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_rename_test_set_mcq_score_test_set_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mcq_score',
        ),
    ]
