# Generated by Django 3.2.5 on 2022-03-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_delete_mcq_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('test_set_new', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
