# Generated by Django 3.2.5 on 2022-03-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_mcq_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.TextField(blank=True)),
                ('disease', models.TextField(blank=True)),
            ],
        ),
    ]
