# Generated by Django 3.2.5 on 2022-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0008_diagnose'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='disease_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
