# Generated by Django 3.2.5 on 2022-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0010_remove_diagnose_disease_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='test_set_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
