# Generated by Django 3.2.5 on 2022-02-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_theory_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image_organ',
        ),
        migrations.AddField(
            model_name='lesson',
            name='disease_line',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_organ1',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_organ2',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theory_progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image_prevention',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
