# Generated by Django 3.2.5 on 2022-02-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20220213_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='disease_line',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
