# Generated by Django 3.2.5 on 2022-02-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_disease_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='disease_line',
        ),
    ]
