# Generated by Django 3.2.5 on 2022-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_disease_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
