# Generated by Django 3.2.5 on 2022-03-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_lesson_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=50)),
                ('filename', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('prior_malignancies', models.CharField(max_length=50)),
                ('primary_tumor_site', models.TextField(blank=True)),
                ('alcohol_history', models.CharField(max_length=50)),
                ('smoking_history', models.TextField(blank=True)),
                ('cancer_type', models.TextField(blank=True)),
                ('basic_cancer_type', models.TextField(blank=True)),
                ('disease_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', unique=True)),
            ],
        ),
    ]
