# Generated by Django 3.2.5 on 2022-03-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_pc',
            name='disease_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
